name: Deploy To Apps Script

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name for manual trigger'
        required: true
        default: "Manual Trigger"
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .clasprc.json file
        run: |
          TEMP_FILE=$(mktemp)
          echo "${{ secrets.CLASPRC_JSON }}" > "$TEMP_FILE"
          cp "$TEMP_FILE" .clasprc.json
          rm "$TEMP_FILE"
      
      - name: Install Clasp locally
        run: npm install -D @google/clasp

      - name: Authenticate Clasp
        run: |
          npm run glogin --creds .clasprc.json

      - name: Install Deps
        run: |
          npm ci --legacy-peer-deps

      - name: Deploy
        run: |
          npm run deploy

      - name: Clasp logout
        run: |
          npm run glogout
