name: Deploy To Apps Script

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name for manual trigger'
        required: true
        default: "Manual Trigger"
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Create .clasprc.json file'
        run: |
          rm -rf ~/.clasprc.json
          touch ~/.clasprc.json
          echo "{ token": { >> ~/.clasprc.json
          echo "access_token": "${{ secrets.AS_TOKEN }}", >> ~/.clasprc.json
          echo "access_token": "${{ secrets.AS_REFRESHTOKEN }}", >> ~/.clasprc.json
          echo "access_token": "https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/userinfo.profile openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/drive.metadata.readonly", >> ~/.clasprc.json
          echo "access_token": "Bearer", >> ~/.clasprc.json
          echo "access_token": "${{ secrets.AS_IDTOKEN }}", >> ~/.clasprc.json
          echo },  >> ~/.clasprc.json
          echo "isLocalCreds": false  >> ~/.clasprc.json
          echo }  >> ~/.clasprc.json

      - name: Install Deps
        run: |
          npm ci --legacy-peer-deps

      - name: Deploy
        run: |
          npm run deploy
