name: Deploy To Apps Script

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name for manual trigger'
        required: true
        default: "Manual Trigger"
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Deps
        run: npm ci --legacy-peer-deps

      - name: Create clasp.json
        env:
          SCRIPT_ID: ${{ secrets.AS_SCRIPTID }}
        run: echo '{"scriptId":"'$SCRIPT_ID'","rootDir":"dist"}' > .clasp.json

      - name: Create folder structure
        run: mkdir -p /home/runner

      - name: Create clasprc.json
        env:
          CLASPRC: ${{ secrets.CLASPRC_JSON }}
        run: echo "$CLASPRC" > /home/runner/.clasprc.json

      - name: Deploy
        run: npm run deploy
